name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: 	windows-2019  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test
    
    - name: setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ matrix.nuget }}
      
    - name: install dependencies
      run: nuget restore $Env:GITHUB_WORKSPACE\DotApp.sln
      
    - name: Build DotNET
      run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\DotApp.sln /p:OutputPath=DotApp.Web /p:PackageAsSingleFile=true /p:DeployOnBuild=true /p:PublishProfile="PPR.pubxml"  /p:WebPublishMethod=Package

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: $Env:GITHUB_WORKSPACE\DotApp.Web
